# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '1 10 * * *'
  push:
    branches:
      - main-xin

permissions:
  contents: write
 
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    
    - name: Set up JDK 8
      uses: actions/setup-java@v5
      with:
        java-version: 8
        distribution: 'zulu'
    
    - name: Cache local Maven repository
      uses: actions/cache@v5
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
        
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    
    - name: Run Java Application
      run: java -jar target/bing-wallpaper-jar-with-dependencies.jar
    
    - name: Save Maven cache
      uses: actions/cache@v5
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
    
    - name: Commit files
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"
        git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        git pull
        if ! git diff --quiet --exit-code; then
          git add README.md bing-wallpaper.md picture docs
          git commit -m "update readme.md"
          git push
        fi
